---
name: Deploy to crates.io
run-name: Deploying to crates.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Mold linker
        uses: rui314/setup-mold@v1

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Determine version bump
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set default version bump to patch
          echo "bump_type=patch" >> $GITHUB_ENV

          # Fetch the last pull request's labels
          PR_LABELS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.ref_name }} | jq -r '.[0].labels | .[].name')

          # Check for labels and determine the bump type
          if echo "$PR_LABELS" | grep -q "release:major"; then
            echo "bump_type=major" >> $GITHUB_ENV
          elif echo "$PR_LABELS" | grep -q "release:minor"; then
            echo "bump_type=minor" >> $GITHUB_ENV
          fi

      - name: Bump version
        run: |
          bump_type=${{ env.bump_type }}
          echo "Bumping version using: $bump_type"
          cargo release version $bump_type --execute --no-confirm

      - name: Commit version bump
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml Cargo.lock
          git commit -m "chore(release): version bump to $(grep '^version = ' Cargo.toml | sed -E 's/version = \"([^\"]+)\"/\1/')"
          git push origin main

      - name: Push changes
        if: steps.update.outputs.updated == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
