---
name: Deploy to crates.io

on:
  workflow_run:
    workflows: ["Bump version based on PR tag"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arthurdw/rust-ci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
