---
name: Deploy to crates.io

on:
  workflow_run:
    workflows: ["Bump version based on PR tag"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: arthurdw/rust-ci:latest

    strategy:
      matrix:
        crate: ["arri_repr", "ronky_derive", "ronky"]
      max-parallel: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Publish ${{ matrix.crate }} to crates.io
        working-directory: ${{ matrix.crate }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
